// Generated by LiveScript 1.2.0
var pickInterpolation, onmessage;
importScripts("prelude-browser-min.js", "perlin.js");
pickInterpolation = function(layer){
  layer.i = {
    stepped: sample1(stepped),
    linear: sample2(linear),
    cosine: sample2(cosine),
    cubic: sample4(cubic),
    catmullrom: sample4(catmullrom)
  }[layer.i];
  return layer;
};
onmessage = function(event){
  var data, layers, res$, i$, ref$, len$, l, sampler, result, to$, y, lresult$, j$, to1$, x;
  data = event.data;
  res$ = [];
  for (i$ = 0, len$ = (ref$ = data.layers).length; i$ < len$; ++i$) {
    l = ref$[i$];
    res$.push(pickInterpolation(l));
  }
  layers = res$;
  sampler = perlin(data.dims, data.level, layers);
  res$ = [];
  for (i$ = 0, to$ = data.dims[0]; i$ < to$; ++i$) {
    y = i$;
    lresult$ = [];
    for (j$ = 0, to1$ = data.dims[1]; j$ < to1$; ++j$) {
      x = j$;
      lresult$.push(sampler([y, x]));
    }
    res$.push(lresult$);
  }
  result = res$;
  return postMessage(result);
};