// Generated by LiveScript 1.2.0
var onmessage;
importScripts("prelude-browser-min.js", "terrain.js");
onmessage = function(event){
  var data, terrain, result, res$, i$, to$, y, lresult$, j$, to1$, x;
  data = event.data;
  terrain = terrainMap(data);
  res$ = [];
  for (i$ = 0, to$ = data.length; i$ < to$; ++i$) {
    y = i$;
    lresult$ = [];
    for (j$ = 0, to1$ = data[y].length; j$ < to1$; ++j$) {
      x = j$;
      lresult$.push(terrain(x, y));
    }
    res$.push(lresult$);
  }
  result = res$;
  return postMessage(result);
};